server:
  port: 8084

spring:
  application:
    name: hc-config-service

eureka:
  instance:
    hostname: 127.0.0.1
  client:
     service-url:
       defaultZone: http://127.0.0.1:8081/eureka/
     #将服务注册到eureka 上
     register-with-eureka: true
     #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
     fetchRegistry: true
